# Generated by Django 5.0.2 on 2024-02-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionServer',
            fields=[
                ('pid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('port', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('totalSpace', models.CharField(max_length=50)),
                ('freeSpace', models.CharField(max_length=50)),
                ('usedSpace', models.CharField(max_length=50)),
            ],
        ),
    ]
